src/hooks/useStorage/index.ts, src/hooks/useStorage/useLocalStorage.ts, src/hooks/useStorage/useSessionStorage.ts, src/hooks/useStorage/useStorage.ts
useStorage hook을 추가했습니다.
**사용 방법**
```tsx
import { useLocalStorage } from '@hooks/useStorage' // useLocalStorage 사용
import { useSessionStorage } from '@hooks/useStorage' // useSessionStorage 사용
```
- index.ts: useLocalStorage와 useSessionStorage를 export 합니다.
- useStorage.ts: useLocalStorage와 useSessionStorage의 base가 되는 파일입니다.
- useLocalStorage.ts: useStorage로부터 localStorage를 좀 더 사용하기 편하게 만든 파일입니다.
- useSessionStorage.ts: useStorage로부터 sessionStorage를 좀 더 사용하기 편하게 만든 파일입니다.
기본적으로 테스트는 해 보았는데, 사용하시다가 또는 테스트 해보시다가 버그를 발견하셨다면 제보 부탁드립니다.
close #21
=> [Feat] useStorage hook 추가

src/components/Header/index.tsx, src/components/Header/styles.tsx
대부분의 페이지에서 사용될 헤더를 구현하였습니다.
[로그인 전]
[로그인 후]
`Components/Header` 에 넣어두었고 그대로 import해서 사용해주시면 됩니다!
로그인 여부에 따라서 다른 버튼이 나오도록 구현해 두었습니다.
- props에 `isLogin` 유무에 따라서 바뀝니다!
메인 화면에 문제 수가 많아질 것을 대비해서 헤더를 상단에 fixed로 설정해 두었습니다.
- CSS상에서 해당 헤더만큼의 크기를 가지는 빈 div ( HeaderSpacer)을 넣어 두었기 때문에 레이아웃에는 영향을 주지 않습니다.
> [20df37f](https://github.com/prgrms-fe-devcourse/FEDC2_CheQuiz_Gidong/commit/20df37f1e2dba8212ba30c645899c39fcf6b01cb) - 헤더 컴포넌트를 구현했습니다.
- 헤더를 fixed로 설정했는데, 어떻게 생각하시는지 궁금합니다.
- 혹시 추가 / 삭제 필요한 버튼이 있으면 말씀해주세요!
- 디자인 화면에 있던 헤더 크기가 너무 커서, 유튜브 기준 두께(3.5rem)으로 변경하였습니다. 전반적인 크기나 디자인 괜찮은지 궁금합니다!
close #26
=> [Feat] 공통 컴포넌트: 헤더 추가

.husky/pre-commit, package.json
lint-staged 관련 스크립트 수정했습니다
b11dcb70b06551c8da596f6e515df88e821e5e7d
> 타입 검사는 husky에서 하고 lint와 prettier는 lint-staged에서 담당합니다
close #51
=> [Fix] lint staged 이슈

src/api/QuizServices.ts, src/pages/QuizSolvePage/index.tsx
- 오늘 새롭게 올라온 api에 대응하였습니다.
- QuizSolvePage의 비즈니스 로직에 전반적인 개선이 있었습니다.
`localhost:3000/solve`이동 후 테스트
1. 사용자가 `/solve` 페이지에 진입하면, 세션스토리지에 존재하는 user-answers와 post-ids 정보를 삭제합니다.
2. 사용자가 문제를 해결합니다. 문제를 모두 해결하면 제출 버튼을 누를 수 있습니다.
3. 제출 버튼을 누를 때 sessionStorage에 사용자가 선택한 정답 정보와 result page에서 fetch할 post id 정보를 저장합니다.
- 기존에는 post Id를 서버로부터 받은 뒤, post id를 hook을 이용하여 저장, post id를 이용하여 하나씩 퀴즈를 불러왔는데, 개선된 로직에서는 post 객체로부터 우선 퀴즈 배열을 만든 뒤, post id는 따로 관리하지 않고 제출 시 quiz 배열로부터 id를 맵핑하여 저장합니다.
- 랜덤으로 퀴즈를 불러올 경우와 set로부터 퀴즈를 불러올 때 로직의 일관성 증가
- 데이터 무결성 개선
- 3aa4e00: QuizService 폴더를 api로 이동
- 1463dd4: 비동기 api 연결
- 7c7997f: 변경된 api에 대응
- 제가 테스트할 때에는 로직 상 별 다른 문제점을 발견하지 못했는데, 혹시 발견하게 되신다면 꼭 리뷰 부탁드립니다. 감사합니다.
- UI적으로 로딩을 추가하여 다음 PR에 반영할 예정입니다.
- 변경된 api를 QuizResultPage에도 이용할 예정이니, 빠르게 리뷰해주시면 감사하겠습니다.
close #67
=> [Feat] QuizSolvePage api 연결

src/pages/QuizResultPage/index.tsx
merge 후 경로 반영 및 api 에러 수정
close #87
=> [Fix] merge 후 경로 반영 및 api 에러 수정

package.json, src/contexts/AuthContext/index.tsx, src/interfaces/SignUpFormData.d.ts, src/interfaces/UserAPI.d.ts, yarn.lock
- 회원가입 시 username의 default 값을 추가했습니다
d1c17c675f621c2ebc69542c27e0c0c6b0dcf9b0
> 인터페이스 추가
f971c36667945fe432cbcb8a8218559440107ca2
> 회원가입 시 username 추가
close #89
=> [Feat] 회원가입 시 기본정보 추가

src/components/Home/QuizSetCard/index.tsx, src/components/Home/QuizSetCard/styles.tsx, src/components/Home/QuizSetList/index.tsx, src/components/Home/QuizSetList/styles.tsx, src/components/Home/RandomQuiz/index.tsx, src/components/Home/RandomQuiz/styles.tsx, src/pages/Home.tsx, src/pages/QuizCreate.tsx, src/pages/Ranking/index.tsx, src/routes/Router.tsx
PR 단위 줄이기 위해서, 메인 페이지 디자인 부분 먼저 올립니다.
- Header 적용
- 현재 작업 중인 페이지 (Home, Create, Ranking) 에 Header 적용했습니다. 
- 메인 페이지 디자인
- RandomQuiz 퀘스트 부분과 QuizSet 지식사냥터 부분 나누어서 디자인 적용하였습니다.
- RandomQuiz 라는 컴포넌트 명과 내부 스타일드 컴포넌트의 네이밍이 급하게 지어서, 불만족스러운데, 딱히 떠오르는 이름들이 없어 우선 진행했습니다. 더 나은 네이밍 있으시다면 제시해주세요 ㅎㅎ
- 메인페이지 남은 작업 알림
- 메인페이지 Context연결 작업 (오늘 중)
-  검색 및 정렬 (내일 오전)
closed #72
=> [Feat] 메인 페이지 UI 디자인

src/App.tsx, src/api/create.ts, src/components/Form/Select/index.tsx, src/components/Form/Select/styles.tsx, src/components/Home/QuizSetList/index.tsx, src/components/Home/QuizSetList/styles.tsx, src/components/Home/RandomQuiz/index.tsx, src/components/Home/RandomQuiz/styles.tsx, src/components/QuizCreate/QuizItem/index.tsx, src/components/QuizCreate/index.tsx, src/constants/index.ts, src/contexts/QuizContext/index.tsx
- QuizContext 추가
- Select Custom컴포넌트화
- 퀴즈생성시 user token -> User 객체 보내주도록 수정
수정,추가 섞에 있어 commit 별로 보시는 것을 강력 추천드립니다.
PR, 이슈제목과는 다르게, 퀴즈생성 수정과 Select컴포넌트 refactor가 포함되었습니다....
마지막에 급하게 눈에 보이는 것 빠르게 처리하느라 이해부탁드려요..
closed #73
=> [Feat] 메인페이지 랜덤퀴즈 및 퀴즈세트 API 연동

src/api/UserServices.ts, src/components/Modal/NicknameModal.tsx, src/components/Modal/PasswordModal.tsx, src/components/UserInfo/UserInfoCard/styles.tsx, src/interfaces/ChangeFormData.d.ts, src/interfaces/UpdateNameFormData.d.ts, src/pages/UserInfoPage/index.tsx, src/pages/UserInfoPage/styles.tsx, src/utils/validation.ts
- 해당 PR은 #80 브랜치에서 따서 만들어진 내용들입니다. 80번 머지에 따라 rebase 완료했습니다!
로그인 된 상태로, 내 id와 일치하는 id의 페이지로 들어가면 " 닉네임 변경, 비밀번호 변경 " 버튼이 생성됩니다.
닉네임 변경, 비밀번호 변경 버튼을 누르면 모달 폼이 나타나고 정상 작동됩니다.
- 모달폼은 현재 모달 바깥부분 클릭 시 사라지는 기능만 구현 되어 있습니다. ( esc로 사라지기 X)
- 비밀번호 변경은 당장 확인할 방법이 없어서 일단 성공적으로 변경되면 나타나는 텍스트를 그대로 콘솔에 출력시켰습니다.
- 현재는 닉네임 변경 시 바로 새로고침 시켜 바뀐 데이터를 불러오도록 하였습니다 ( 나중에 리팩토링 예정입니다..)
http://localhost:3000/user/62aafe7ce193b3692eddfc77 로 접속
- 이 때는 이 아이디/비번으로 로그인 안된 상태라 버튼이 뜨지 않습니다.
id : mihae@test.com
pw : qwerqwer 
로 로그인
- 이 때는 닉네임 변경, 비밀번호 변경 버튼이 뜹니다.
버튼 컴포넌트 디자인 ( 닉네임 변경, 비밀번호 변경) 관련
- 기본 디자인에는 UserCard 내부에 버튼이 들어있는 형식이었는데, 다른 페이지에서 사용 중인 UserCard에 props 등을 추가하는 것이 맞는지 고민되었습니다. UserCard 종속이 아닌, UserPage 종속이 되어야 맞다고 생각해서 위치를 바꾸게 되었습니다. 
- 기왕이면 게임 요소를 살리고 싶다고 생각해서 다이어리에 붙은 포스트잇 같은 느낌으로 구현해보았습니다..!
> …
=> [Feat] 닉네임, 비밀번호 변경 로직 구현

src/pages/QuizResultPage/index.tsx
ResultPage 진입 로직을 구현하였습니다.
사용자는 어떤 페이지에 있는지에 상관 없이, 가장 마지막으로 해결한 문제 세트의 결과를 확인할 수 있습니다.
1. 사용자가 `/solve`페이지를 통해 문제를 푼다
2. `/result`에 진입할 때, 세션스토리지에 저장된 post-id와 user-answer 배열 길이를 비교한다.
3. post-id 배열이 0이라면 더 이상 비교하지 않고 error 페이지로 이동한다.
4. post-id와 user-answer 배열의 길이가 다르다면, error 페이지로 이동한다.
- 사용자가 문제를 풀지 않고 바로 result page로 진입 시
- 사용자가 문제를 해결하고 result page로 진입 시
- 문제를 해결하고 난 뒤 아무 페이지에서 `/result`로 진입 시
- 497b31c: 진입 로직을 구현하였습니다.
- ed9b19b: 약간의 리팩토링을 진행하였습니다.
해당 부분을 테스트 해보긴 했으나, 다른 버그 발견시 알려주시면 빠르게 고치겠습니다.!!
close #102
=> [Feat] QuizResultPage 진입 경로 제한 설정

src/components/QuizCreate/QuizItem/index.tsx, src/components/QuizCreate/QuizList/index.tsx, src/components/QuizCreate/index.tsx, src/hooks/useValidation/index.tsx, src/utils/validation.ts
=> [Feat] 퀴즈 생성 Form Validation 추가

src/components/QuizResult/index.tsx, src/components/QuizResult/styles.tsx
- result page에 프로필 이미지를 추가하였습니다.
close #112
=> [Feat] 프로필 이미지 추가

src/api/notification.ts, src/components/Form/Title/styles.ts, src/components/Header/index.tsx, src/components/Header/styles.tsx, src/components/LoginForm/index.tsx, src/components/Modal/index.tsx, src/components/Modal/styles.tsx, src/components/Notification/Item.tsx, src/components/Notification/index.tsx, src/components/Notification/styles.ts, src/components/SignUpForm/index.tsx, src/interfaces/NotificationAPI.d.ts, src/interfaces/UserAPI.d.ts, src/pages/Home.tsx, src/pages/QuizCreate.tsx, src/pages/QuizResultPage/index.tsx, src/pages/Ranking/index.tsx
=> [Feat] 알림 목록

src/api/auth.ts, src/components/Header/index.tsx, src/components/Header/styles.tsx, src/components/LoginForm/index.tsx, src/components/Modal/index.tsx, src/components/SignUpForm/index.tsx, src/contexts/AuthContext/index.tsx
- 로그아웃 기능을 추가했습니다
- 회원가입 모달 오류 해결했습니다
- modal 상태 이름 변경했습니다
- 로그아웃 API가 있어서 사용하기는 했는데 의미가 없어보이기는 하네요 ㅎ
close #118
=> [Feat] 로그아웃 기능 추가

src/components/Notification/Item.tsx, src/components/Notification/index.tsx
- 알림 목록 관련 오류를 수정했습니다
- 알림이 없다면 목록에서 '알림이 없습니다'를 표시합니다
- 알림 관련 초기값을 수정했습니다
close #119
=> [Fix] 알림 목록 표시 수정

src/components/QuizResult/index.tsx
- getUserPoints 함수에서 토큰 파싱 에러 현상을 수정했습니다.
close #121
=> [Fix] 토큰  파싱 오류 수정

src/App.tsx, src/components/Home/QuizSetCard/index.tsx, src/components/Home/QuizSetCard/styles.tsx, src/components/Home/QuizSetList/index.tsx, src/components/Home/QuizSetList/styles.tsx, src/components/Home/RandomQuiz/styles.tsx
[fix]
- 카드 width 고정되어 있어, 가운데 정렬 되지 않던 것 수정
- 카드에서 난이도n 이 아닌 문제 개수를 보여주어 어느정도 빠르게 풀 수 있을지 제공
- 기본채널 퀴즈세트와 같이 내용이 긴 퀴즈카드의 경우 카드 밖으로 흘러 넘치는 현상 수정
[style]
- 카드 리스트 짝수 마다 살짝 내려주어, 파도를 연상시키도록 스타일 수정
- 일일퀘스트 input center 맞춤
- 카드 description 줄바꿈 적용하여 가독성 증가
- 메인 페이지 카드리스트(grid)에 반응형 적용
closed #125
=> [Fix] 메인페이지 디자인 수정

src/api/QuizServices.ts, src/api/user.ts, src/components/QuizResult/index.tsx, src/components/QuizResult/styles.tsx, src/pages/QuizResultPage/index.tsx, src/pages/QuizResultPage/styles.tsx, src/pages/QuizSolvePage/index.tsx, src/pages/UserInfoPage/index.tsx
=> [Fix] QuizResultPage 디자인 수정

src/components/QuizCreate/QuizItem/index.tsx, src/components/QuizCreate/QuizItem/styles.tsx, src/utils/validation.ts
validation 색상 변경 및 위치 조절하여, 최대한 form 레이아웃의 변화가 없도록 수정하였습니다.
퀴즈세트 부분 조금 건드려보려고 했는데, 하나의 폼안에서 퀴즈화 세트 여부에 따라 validation 처리하기가 까다로워서 일단은 Adv 로 넘겨야 할 것 같아요 ㅠ.ㅠ
마지막에 조금 피곤해서, 코드 정리를 꼼꼼히 못한 것 같네요 ㅠ.ㅠ 
한 숨 자고 일어나서, 마지막 rank 페이지 디자인 수정해볼게요.
closed #127
=> [Fix] 퀴즈 생성 페이지 Validation 디자인 적용

src/containers/UserRankList/index.tsx, src/containers/UserRankList/style.tsx, src/pages/Ranking/index.tsx, src/pages/Ranking/style.tsx, src/styles/theme.ts
=> [Fix] 랭킹페이지 디자인 수정

src/components/QuizResult/styles.tsx
해설 부분 가독성 개선을 위해 줄바꿈 속성 적용했습니다.
전 -> 후
closed #142
=> [fix] result페이지 해설 부분 줄바꿈 적용

src/components/Header/index.tsx
- #144 이슈 해결입니다
- 이 부분 조금? 크리티컬하다 생각해서 반영이 필요할 것 같습니다 :)
close #144
=> [fix] 로그아웃 시 알림 모달 꺼지지 않는 현상 수정

src/foundations/colors/index.ts, src/foundations/index.ts
색상 값 규격화를 위한 color foundation 을 구현했습니다.
- 색상 이름으로 되어 있던 부분을, scale 단위로 변경하였습니다. 
- ex) GRAY_300
- 태그 등에서 다양한 색상이 사용되고 있는데, 색상 별로 이름을 붙이기 보다는 scale 단위를 차용하기로 했습니다.
[디자인시스템 문서 확인하기](https://www.figma.com/file/VPEGB2a6MBbT4zbDTBIcfr/CheQuiz-%EB%94%94%EC%9E%90%EC%9D%B8%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=2%3A956)
- 기존의 색상을 scale 단위 안에 최대한 넣었으나, 변경된 값도 일부 있습니다. ( 태그의 yellow, green, blue)
- 다른 태그에 비해 색이 진하다고 생각해 조금 연한 색으로 바꾸었습니다.
- 혹시 이전 값이 낫다고 생각하시면 말씀해주세요!  
- 저희가 구현할 컴포넌트에서는, 관련 옵션을 받아 선택지를 줄일 예정입니다.
[ 예시 ) 확정 X ]
```js
//사용 시
<Test type="mainBtn"/>
// styled 컴포넌트 정의
export const Test = styled.div`
background-color:  ${({type})=>type === "mainBtn"? BRAND_COLOR :PRIMARY }
`
```
- 개인적인 컴포넌트에서 색이 필요할때는 그냥 import 해서 사용하시면 됩니다.
```js
import { GRAY_100 } from '@/foundations';
color: GRAY_100;
``` …
=> [Feat]  Color foundation 구현

src/components/Form/Select/styles.tsx, src/components/Home/QuizSetList/styles.tsx, src/components/Home/RandomQuiz/index.tsx, src/pages/QuizSolvePage/index.tsx, src/pages/QuizSolvePage/styles.tsx
어제 커피챗에서 나왔던 fix 사항들 크게 어렵지 않아서 빠르게 fix 해보았습니다.
이슈 제목은 메인페이지로 했는데, quizSolve 페이지 버튼 이슈도 같이 PR에 넣었습니다..^..^...
커밋 별로 보시면, 쉽고빠르게 볼 수 있습니다.
closed #147
=> [Fix] 메인페이지 UI 디테일 수정
